[custom]

; 内联规则（如果需要启用，请取消下一行的分号 ;）
; rules=DOMAIN-SUFFIX,argotunnel.com,☁ Cloudflare

; 设置规则标志位
; 本地地址和域名直连
ruleset=🎯 全球直连,[]GEOSITE,private
ruleset=🎯 全球直连,[]GEOIP,private,no-resolve
; 本项目收录的直连规则
ruleset=🎯 全球直连,https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.mrs,28800
ruleset=🎯 全球直连,https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
; 本项目收录的代理规则
ruleset=🚀 手动选择,https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Domain.mrs,28800
ruleset=🚀 手动选择,https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical_IP.yaml,28800
; 谷歌在国内可用的域名直连
ruleset=🎯 全球直连,[]GEOSITE,google-cn
; 国内游戏域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
; Steam 下载 CDN 直连
ruleset=🎯 全球直连,https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Domain.mrs,28800
ruleset=🎯 全球直连,https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical_IP.yaml,28800
; 各大游戏平台下载域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-game-platforms-download
; BT Tracker 相关域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=🐙 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/my_REJECT.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=👮‍♂️ Work,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/work_RULES.list
ruleset=📝 MyRules,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/my_RULES.list
ruleset=☁ Cloudflare,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/Cloudflare.list
ruleset=☁ Cloudflare,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Cloudflare/Cloudflare.list
ruleset=☁ Cloudflare,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Cloudflarecn/Cloudflarecn.list
ruleset=🇭🇰 香港节点,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/HK.list
ruleset=🇹🇼 台湾节点,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/TW.list
ruleset=💬 Ai,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/ai.list
ruleset=💰 Bitcoin,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/Bitcoin.list
ruleset=🆓 FREE节点,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/cf.list
ruleset=🕹 Game,https://raw.githubusercontent.com/happy8109/clash/refs/heads/main/game_RULES.list
ruleset=🕹 Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🐳 Docker,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Docker/Docker.list
ruleset=🐳 Docker,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Npmjs/Npmjs.list
ruleset=🐳 Docker,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Ubuntu/Ubuntu.list
ruleset=💰 Bitcoin,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Crypto/Crypto.list
ruleset=💬 Ai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=💬 Ai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
ruleset=💬 Ai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=💬 Ai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list
ruleset=🎵 AppleMusic,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMusic/AppleMusic.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🌐 地区选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🎮 PlayStation,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Sony.list
ruleset=🌐 地区选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
; 由于 OpenClash 使用的大陆白名单收录不全，此处留有 geosite:cn 作为国内域名兜底
ruleset=🎯 全球直连,[]GEOSITE,cn
; 由于 OpenClash 使用的大陆白名单收录不全，此处留有 geoip:cn 作为国内 IP 兜底
ruleset=🎯 全球直连,[]GEOIP,cn,no-resolve
; PT/BT 优化开启会使 80/443 以外端口的流量直连
ruleset=🔀 非标端口,https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,28800
; 国内冷门域名会命中漏网之鱼
ruleset=🐟 漏网之鱼,[]FINAL
; 设置规则标志位结束

; 设置分组标志位
custom_proxy_group=👮‍♂️ Work`select`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=📝 MyRules`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🆓 FREE节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=💬 Ai`select`[]DIRECT`[]📍 手动切换`.*(美国|台|坡|US|TW|SG)
custom_proxy_group=💰 Bitcoin`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=🕹 Game`select`[]🌐 地区选择`.*(Game|遊戲專用)`[]📍 手动切换`[]DIRECT
custom_proxy_group=🎮 PlayStation`select`[]🌐 地区选择`[]♻️ 自动选择`[]🕹 Game`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=☁ Cloudflare`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=🐙 GitHub`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=🐳 Docker`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=📲 电报消息`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🌐 地区选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]📍 手动切换
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]📍 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🌐 地区选择`[]♻️ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]📍 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🌐 地区选择`[]♻️ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]📍 手动切换
custom_proxy_group=🎵 AppleMusic`select`[]DIRECT`[]🌐 地区选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]📍 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🌐 地区选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]📍 手动切换
custom_proxy_group=🎥 奈飞视频`select`^(?!.*(Game|遊戲專用).*)
custom_proxy_group=♻️ 自动选择`url-test`[]DIRECT`^(?!.*(Game|遊戲專用).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌐 地区选择`select`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🆓 FREE节点`[]DIRECT
custom_proxy_group=📍 手动切换`select`^(?!.*(Game|遊戲專用).*)
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🌐 地区选择`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🆓 FREE节点`[]📍 手动切换
custom_proxy_group=🔀 非标端口`select`[]🐟 漏网之鱼`[]🎯 全球直连
custom_proxy_group=🇭🇰 香港节点`url-test`(🇭🇰|港|\bHK(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(🇸🇬|新加坡|坡|狮城|\bSG(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(🇹🇼|台|新北|彰化|\bTW(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(🇰🇷|\bKR(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Korea|KOREA|KOR|首尔|韩|韓|春川|Chuncheon|ICN)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🆓 FREE节点`url-test`(CF|vl.8109|cf|联通|移动|电信|Hug)`https://cp.cloudflare.com/generate_204`300,,50
; 设置分组标志位结束

clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

; 全局设置
enable_rule_generator=true
overwrite_original_rules=true
